
version: 2

sources:
  - name: calabaza_mc
    database: telegram_bot
    schema: calabaza_bot
    description: related to the calabaza bot
    tables:
      - name: morning_check_in
        description: >
          data related to the morning check ins.

models:
    - name: morning_view_model
      description: "A cleaned up source of /morning to get data from for reports"
      columns:
          - name: created_at_utc
            description: "Datetime log entry was created."
            tests:
                - not_null
                - unique
